apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
    spec:
      containers:
      - name: webserver
        image: omrik91/task-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
  - name: webserver-service
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
    nodePort: 31000